# Generated by Django 5.1.2 on 2024-10-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('AccNo', models.IntegerField(primary_key='AccNo', serialize=False)),
                ('IFSC_Coad', models.CharField(max_length=20)),
                ('Loan_Amount', models.IntegerField()),
                ('Time_Period', models.FloatField()),
                ('Rate_of_Interest', models.FloatField()),
                ('PhoneNo', models.IntegerField()),
            ],
        ),
    ]
